config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                             root GET      /                                       mains#top
#                        mains_top GET      /mains/top(.:format)                    mains#top
#                 new_user_session GET      /users/sign_in(.:format)                users/sessions#new
#                     user_session POST     /users/sign_in(.:format)                users/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               users/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           users/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          users/passwords#edit
#                    user_password PATCH    /users/password(.:format)               users/passwords#update
#                                  PUT      /users/password(.:format)               users/passwords#update
#                                  POST     /users/password(.:format)               users/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 users/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                users/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   users/registrations#edit
#                user_registration PATCH    /users(.:format)                        users/registrations#update
#                                  PUT      /users(.:format)                        users/registrations#update
#                                  DELETE   /users(.:format)                        users/registrations#destroy
#                                  POST     /users(.:format)                        users/registrations#create
#                  new_user_unlock GET      /users/unlock/new(.:format)             devise/unlocks#new
#                      user_unlock GET      /users/unlock(.:format)                 devise/unlocks#show
#                                  POST     /users/unlock(.:format)                 devise/unlocks#create
#                            users GET      /users(.:format)                        users#index
#                             user GET      /users/:id(.:format)                    users#show
#                letter_opener_web          /letter_opener                          LetterOpenerWeb::Engine
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  root 'mains#top'
  get 'mains/top'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  name                   :string           default(""), not null
#  username               :string           default(""), not null
#  website                :string           default("")
#  bio                    :text             default("")
#  email                  :string           default(""), not null
#  phone                  :string           default("")
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  gender                 :integer          default("not_specified")
#  provider               :string
#  uid                    :string
#  avatar                 :string
#

class User < ApplicationRecord
  attr_writer :login

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: %i[facebook]

  enum gender: { not_specified: 0, female: 1, male: 2 }

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9_\.]*\Z/
  # VALID_URL_REGEX = /\A(http|https):\/\/[a-zA-Z0-9]*\.[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}\/[a-zA-Z0-9]*\Z/
  validates :name, presence: true, case_sensitive: false
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       format: { with: VALID_USERNAME_REGEX }
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }
  # 利便性を考えると厳密なURLの正規表現は設定しない方がいいかも
  # validates :website, allow_blank: true,
  #                     format: { with: VALID_URL_REGEX }
  validates :bio, allow_blank: true,
                  length: { maximum: 500 }
  # 電話番号はstringの方が扱いやすいかも、ただ厳密に考えるには手間がかかる
  # validates :phone, allow_blank: true,
  #                   numericality: { only_integer: true }
  validates :gender, presence: true,
                     inclusion: { in: User.genders.keys }
  validate :validate_username
  validate :avatar_size

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    conditions[:email]&.downcase!
    login = conditions.delete(:login)

    where(conditions.to_hash).where(
      ['lower(username) = :value OR lower(email) = :value',
       { value: login.downcase }]
    ).first
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.username = auth.info.username
      user.website = auth.info.link
      user.password = Devise.friendly_token[0, 20]
      user.remote_avatar_url = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"]
        user.email = data["extra"]["raw_info"]["email"] if user.email.blank?
        user.name = data["extra"]["raw_info"]["name"] if user.name.blank?
        user.username = data["extra"]["raw_info"]["username"] if user.username.blank?
        user.website = data["extra"]["raw_info"]["link"] if user.website.blank?
        user.password = Devise.friendly_token[0, 20]
        user.provider = data["provider"] if user.provider.blank?
        user.uid = data["uid"] if user.uid.blank?
        user.remote_avatar_url = data["info"]["image"] if user.avatar.blank?
      end
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id",
               user_id: id).order(created_at: :desc)
  end

  private

    def validate_username
      errors.add(:username, :invalid) if User.where(email: username).exists?
    end

    def avatar_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "should be less than 5MB")
      end
    end
end

app/controllers/concerns/users.rb
module Users
  extend ActiveSupport::Concern

  def get_users(input_words)
    if input_words
      User.where('username LIKE ?', "%#{input_words}%")
    else
      User
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :user_signed_in?

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.nil?
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    else
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    end
  end

  # GET|POST /users/auth/providers/callback
  def failure
    flash[:alert] = "Something went wrong!"
    redirect_to new_user_registration_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def after_update_path_for(resource)
      user_path(resource)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Users

  before_action :authenticate_user!
  before_action :set_user, except: [:index]

  def show
  end

  def index
    @users = get_users(params[:search]).paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = 'Your profile was successfully updated.'
    else
      render :edit
      flash[:alert] = 'Update failed.'
    end
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :username, :website, :bio, :email, :phone, :gender, :avatar)
    end
end

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/users/shared/_login.html.erb
<div class="card my-4">
  <div class="card-body">
    <div class="text-center">
      <span><%= image_tag("instagram-new-logo.png", style: "height:60px; margin-bottom:10px;") %></span>
    </div>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group">
        <%= f.text_field :login,
                          autofocus: true,
                          placeholder: "Username or email",
                          class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password,
                             autocomplete: "off",
                             placeholder: "Password",
                             class: "form-control" %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>

      <div class="actions">
        <%= f.submit "Log in", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
    <hr>
    <%= render 'users/shared/omniauth', devise_mapping: Devise.mappings[:user] %>
    <div class="mt-3">
      <%= render "users/shared/links" %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body text-center">
    <span>Don't have an account?</span>
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name) %><br />
    <% end -%>
  </div>
</div>

app/views/users/shared/_omniauth.html.erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to omniauth_authorize_path(resource_name, provider) do %>
      <div class="btn btn-primary btn-block">
        <span><%= icon('fab', 'facebook') if provider == :facebook %></span>
        <%= "Login in with #{OmniAuth::Utils.camelize(provider)}" %>
      </div>
    <% end %>
  <% end -%>
<% end -%>

app/views/users/shared/_signup.html.erb
<div class="card" style="margin:20px 0;">
  <div class="card-body">
    <div class="logo text-center" style="margin-bottom:10px;">
      <span><%= image_tag("instagram-new-logo.png", style: "height:60px;") %></span>
    </div>
    <div class="text-center" style="margin-bottom:10px;">
      <span class="text-secondary font-weight-bold">Sign up to see photos and videos from your friends.</span>
    </div>

    <% unless session['devise.facebook_data'] %>
      <%= render 'users/shared/omniauth' %>
    <% end %>
    <hr>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="form-group">
        <%= f.email_field :email,
                          autofocus: true,
                          placeholder: "Email",
                          class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :name,
                         placeholder: "Full Name",
                         class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :username,
                         placeholder: "Username",
                         class: "form-control" %>
      </div>

      <% unless session["devise.facebook_data"] %>
        <div class="form-group">
          <%= f.password_field :password,
                               autocomplete: "off",
                               placeholder: "Password",
                               class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password_confirmation,
                               autocomplete: "off",
                               placeholder: "Password Confirmation",
                               class: "form-control" %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "Sign up", class: "btn btn-primary btn-block mb-3" %>
      </div>

      <% if session["devise.facebook_data"] %>
        <div class="actions">
          <%= link_to cancel_user_registration_path do %>
            <div class="btn btn-warning">
              Cancel sign up with Facebook
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <div class="terms text-center text-secondary my-3">
      <span>By signing up, you agree to our
        <a href="https://termsfeed.com/terms-service/39629cd6976c4185c0d0d43bf2e1baa8">Terms</a>,
        <a href="https://www.freeprivacypolicy.com/privacy/view/ea7b8480c5f17b306c4a83612a7969c3">Data Policy</a> and
        <a href="https://cookiepolicygenerator.com/live.php?token=lTlLYabGtHyvqc47asECZkJn08CKvqkI">Cookies Policy</a>.
      </span>
    </div>

    <%= render "users/shared/links" %>
  </div>
</div>

<div class="card">
  <div class="card-body text-center">
    <span>Have an account?</span>
    <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end -%>
  </div>
</div>