config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                             root GET      /                                       mains#top
#                        mains_top GET      /mains/top(.:format)                    mains#top
#                 new_user_session GET      /users/sign_in(.:format)                users/sessions#new
#                     user_session POST     /users/sign_in(.:format)                users/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               users/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           users/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          users/passwords#edit
#                    user_password PATCH    /users/password(.:format)               users/passwords#update
#                                  PUT      /users/password(.:format)               users/passwords#update
#                                  POST     /users/password(.:format)               users/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 users/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                users/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   users/registrations#edit
#                user_registration PATCH    /users(.:format)                        users/registrations#update
#                                  PUT      /users(.:format)                        users/registrations#update
#                                  DELETE   /users(.:format)                        users/registrations#destroy
#                                  POST     /users(.:format)                        users/registrations#create
#                  new_user_unlock GET      /users/unlock/new(.:format)             devise/unlocks#new
#                      user_unlock GET      /users/unlock(.:format)                 devise/unlocks#show
#                                  POST     /users/unlock(.:format)                 devise/unlocks#create
#                            users GET      /users(.:format)                        users#index
#                             user GET      /users/:id(.:format)                    users#show
#                letter_opener_web          /letter_opener                          LetterOpenerWeb::Engine
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  root 'mains#top'
  get 'mains/top'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  name                   :string           default(""), not null
#  username               :string           default(""), not null
#  website                :string           default("")
#  bio                    :text             default("")
#  email                  :string           default(""), not null
#  phone                  :string           default("")
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  gender                 :integer          default("not_specified")
#  provider               :string
#  uid                    :string
#  avatar                 :string
#

class User < ApplicationRecord
  attr_writer :login

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: %i[facebook]

  enum gender: { not_specified: 0, female: 1, male: 2 }

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9_\.]*\Z/
  # VALID_URL_REGEX = /\A(http|https):\/\/[a-zA-Z0-9]*\.[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}\/[a-zA-Z0-9]*\Z/
  validates :name, presence: true, case_sensitive: false
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       format: { with: VALID_USERNAME_REGEX }
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }
  # 利便性を考えると厳密なURLの正規表現は設定しない方がいいかも
  # validates :website, allow_blank: true,
  #                     format: { with: VALID_URL_REGEX }
  validates :bio, allow_blank: true,
                  length: { maximum: 500 }
  # 電話番号はstringの方が扱いやすいかも、ただ厳密に考えるには手間がかかる
  # validates :phone, allow_blank: true,
  #                   numericality: { only_integer: true }
  validates :gender, presence: true,
                     inclusion: { in: User.genders.keys }
  validate :validate_username
  validate :avatar_size

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    conditions[:email]&.downcase!
    login = conditions.delete(:login)

    where(conditions.to_hash).where(
      ['lower(username) = :value OR lower(email) = :value',
       { value: login.downcase }]
    ).first
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.username = auth.info.username
      user.website = auth.info.link
      user.password = Devise.friendly_token[0, 20]
      user.remote_avatar_url = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"]
        user.email = data["extra"]["raw_info"]["email"] if user.email.blank?
        user.name = data["extra"]["raw_info"]["name"] if user.name.blank?
        user.username = data["extra"]["raw_info"]["username"] if user.username.blank?
        user.website = data["extra"]["raw_info"]["link"] if user.website.blank?
        user.password = Devise.friendly_token[0, 20]
        user.provider = data["provider"] if user.provider.blank?
        user.uid = data["uid"] if user.uid.blank?
        user.remote_avatar_url = data["info"]["image"] if user.avatar.blank?
      end
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id",
               user_id: id).order(created_at: :desc)
  end

  private

    def validate_username
      errors.add(:username, :invalid) if User.where(email: username).exists?
    end

    def avatar_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "should be less than 5MB")
      end
    end
end

app/controllers/concerns/users.rb
module Users
  extend ActiveSupport::Concern

  def get_users(input_words)
    if input_words
      User.where('username LIKE ?', "%#{input_words}%")
    else
      User
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :user_signed_in?

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.nil?
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    else
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    end
  end

  # GET|POST /users/auth/providers/callback
  def failure
    flash[:alert] = "Something went wrong!"
    redirect_to new_user_registration_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def after_update_path_for(resource)
      user_path(resource)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Users

  before_action :authenticate_user!
  before_action :set_user, except: [:index]

  def show
  end

  def index
    @users = get_users(params[:search]).paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = 'Your profile was successfully updated.'
    else
      render :edit
      flash[:alert] = 'Update failed.'
    end
  end

  def following
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :username, :website, :bio, :email, :phone, :gender, :avatar)
    end
end

app/views/users/_follow.html.erb
<%= link_to user_relationships_path(user_id: user.id),
            method: :post,
            remote: true do %>
  <div class="btn btn-primary">
    Follow
  </div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless user == current_user %>
  <div id="follow_form_<%= user.id %>" style="display:inline;">
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user: user, style: 'display:inline;' %>
  <% else %>
    <%= render 'follow', user: user %>
  <% end %>
  </div>
<% end %>

app/views/users/_getting_started.html.erb
<div class="col-md-12">
  <p style="margin-left:30px;"><b>Getting Started</b></p>
</div>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <div class="text-center">
        <span style="font-size:40px;">
          <i class="fab fa-facebook"></i>
        </span>
        <p>Find Friends from Facebook</p>
      </div>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <div class="text-center">
        <span style="font-size:40px;">
          <i class="fas fa-phone"></i>
        </span>
        <p>Register Your Phone</p>
      </div>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="card">
    <div class="card-body">
      <div class="text-center">
        <span style="font-size:40px;">
          <i class="fas fa-camera"></i>
        </span>
        <p>Add Profile Photo</p>
      </div>
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= link_to user_relationship_path(user_id: current_user.id, id: followed_id(current_user, user)),
            method: :delete,
            remote: true do %>
  <div class="btn btn-outline-info">
    Unfollow
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3 my-2">
  <div class="card">
    <div class="card-body text-center">
      <p>
        <%= link_to user_path(user) do %>
        <%= image_tag(user.avatar.thumb, class: "rounded-circle") %>
        <% end %>
      </p>
      <p><%= user.username %></p>
      <%= render 'follow_form', user: user %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="card my-4">
        <div class="card-body">
          <%= form_with(model: @user, local: true, url: user_path(@user), class: 'user') do |f| %>
            <div class="row">
              <div class="col-md-3 text-right">
                <%= image_tag(@user.avatar.thumb, class: 'rounded-circle',
                                                  style: 'cursor:pointer;',
                                                  onClick:"$('#user_avatar').click()") %>
              </div>
              <div class="col-md-9">
                <p><%= @user.username %></p>
                <span class="upload">
                  <label for="user_avatar" style="color:blue; cursor:pointer;">
                    Change your avatar
                  </label>
                  <%= f.file_field :avatar, id: :user_avatar,
                                            class: 'image-upload',
                                            style: 'display:none;',
                                            accept: 'image/jpeg,image/jpg,image/png' %>
                </span>
              </div>
            </div>

            <script>
              $(document).ready(function(){
                $('#user_avatar').val("");
                $('#user_avatar').change(function(){
                  var array = $('#user_avatar').val();
                  var image_name = array.split("\\");
                  $('#display_user_avatar').html(image_name[2]);
                });

                $('.user').bind('change', function(){
                  var size_in_megabytes = this.files[0].size/1024/1024;
                  if (size_in_megabytes > 5) {
                    alert('Maximum file size is 5MB. Please choose a smaller file.');
                  }
                });
              });
            </script>
            <span id="display_user_avatar"></span>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :fullname %><br />
              </div>
              <div class="col-md-9">
                <%= f.text_field :name, autofocus: true,
                                        placeholder: "Full Name",
                                        class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :username %><br />
              </div>
              <div class="col-md-9">
                <%= f.text_field :username, placeholder: "Username",
                                            class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :website %><br />
              </div>
              <div class="col-md-9">
                <%= f.text_field :website, placeholder: "Your Web Site",
                                           class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :bio %><br />
              </div>
              <div class="col-md-9">
                <%= f.text_area :bio, placeholder: "Please introduce yourself",
                                      class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :email %><br />
              </div>
              <div class="col-md-9">
                <%= f.email_field :email, placeholder: "Email",
                                          class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :phone %><br />
              </div>
              <div class="col-md-9">
                <%= f.text_field :phone, placeholder: "Phone number",
                                         class: 'form-control' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-3 text-right d-none d-md-block d-lg-block">
                <%= f.label :gender %><br />
              </div>
              <div class="col-md-9">
                <%= f.select :gender, User.genders.keys.to_a, {},
                                      class: 'form-control' %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-9 offset-md-3">
                <div class="update-actions">
                  <%= f.submit "Update", class: 'btn btn-primary' %>
                  <%= link_to "Edit password", edit_user_registration_path(current_user),
                                               class: 'btn btn-success' %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="row">
            <div class="col-md-9 offset-md-3">
              <div class="cancel-account my-4">
                <h4>Cancel my account</h4>
                <p>Unhappy?
                  <%= button_to "Cancel my account",
                                registration_path(resource_name),
                                class: 'btn btn-danger',
                                data: { confirm: "Are you sure?" },
                                method: :delete %>
                </p>
              </div>
              <%= link_to "Back", :back %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class="container">
  <div class="row">
    <%= render @users %>
  </div>
  <%= will_paginate @users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.username}") %>
<div class="container">
  <div class="row my-5">
    <div class="col-md-3 offset-md-2">
      <%= image_tag @user.avatar, class: 'rounded-circle',
                                  alt: 'users avatar' %>
    </div>
    <div class="col-md-5">
      <div class="my-4">
        <span class="mr-3"><%= @user.username %></span>
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user) do %>
            <div class="btn btn-outline-secondary">
              Edit Profile
            </div>
          <% end %>
        <% else %>
          <%= render 'follow_form', user: @user %>
        <% end %>
      </div>
      <div class="mb-4">
        <span class="mr-4"><%= @user.posts.count %> posts</span>
        <span class="stats mr-4">
          <%= render 'shared/stats' %>
        </span>
      </div>
      <div>
        <p><b><%= @user.name %></b></p>
        <p><%= @user.bio %></p>
        <p>
          <a href="<%= @user.website %>" target=”_blank”>
            <%= @user.website %>
          </a>
        </p>
      </div>
    </div>
  </div>

  <hr>

  <% if @user == current_user %>
    <div class="row justify-content-center">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="your-posts-tab" data-toggle="pill" href="#your-posts" role="tab" aria-controls="your-posts" aria-selected="true">
            Your Posts
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="liked-posts-tab" data-toggle="pill" href="#liked-posts" role="tab" aria-controls="liked-posts" aria-selected="false">
            Liked Posts
          </a>
        </li>
      </ul>
    </div>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="your-posts" role="tabpanel" aria-labelledby="your-posts-tab">
        <div class="row">
          <% if current_user.posts.blank? %>
            <%= render 'getting_started' %>
          <% elsif @user.posts.blank? %>
            <div class="col-md-12">
              <p class="text-center">There's no post...</p>
            </div>
          <% else %>
            <%= render @user.posts %>
          <% end %>
        </div>
        <%= will_paginate @user.posts.paginate(page: params[:page]), :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
      <div class="tab-pane fade" id="liked-posts" role="tabpanel" aria-labelledby="liked-posts-tab">
        <div class="row">
          <% @user.likes.each do |like| %>
            <%= render like.post %>
          <% end %>
        </div>
        <%= will_paginate @user.likes.paginate(page: params[:page]), :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
    </div>
  <% else %>
    <div class="row">
      <% if @user.posts.blank? %>
        <div class="col-md-12">
          <p class="text-center">There's no post...</p>
        </div>
      <% else %>
        <%= render @user.posts %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <div class="row my-4">
    <aside class="col-md-4">
      <section class="user_info">
        <%= image_tag @user.avatar, class: 'rounded-circle' %>
        <h3><%= @user.username %></h3>
        <p><%= link_to "view profile", @user %></p>
        <span>Posts: <%= @user.posts.count %></span>
      </section>
      <section class="stats">
        <!-- TODO: Follow/Unfollowしたらfollowingの数を更新する -->
        <%#= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h4><%= @title %></h4>
      <div class="row">
        <% if @users.any? %>
          <%= render @users %>
        <% end %>
      </div>
    </div>
  </div>
</div>