config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                             root GET      /                                       mains#top
#                        mains_top GET      /mains/top(.:format)                    mains#top
#                 new_user_session GET      /users/sign_in(.:format)                users/sessions#new
#                     user_session POST     /users/sign_in(.:format)                users/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               users/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           users/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          users/passwords#edit
#                    user_password PATCH    /users/password(.:format)               users/passwords#update
#                                  PUT      /users/password(.:format)               users/passwords#update
#                                  POST     /users/password(.:format)               users/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 users/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                users/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   users/registrations#edit
#                user_registration PATCH    /users(.:format)                        users/registrations#update
#                                  PUT      /users(.:format)                        users/registrations#update
#                                  DELETE   /users(.:format)                        users/registrations#destroy
#                                  POST     /users(.:format)                        users/registrations#create
#                  new_user_unlock GET      /users/unlock/new(.:format)             devise/unlocks#new
#                      user_unlock GET      /users/unlock(.:format)                 devise/unlocks#show
#                                  POST     /users/unlock(.:format)                 devise/unlocks#create
#                            users GET      /users(.:format)                        users#index
#                             user GET      /users/:id(.:format)                    users#show
#                letter_opener_web          /letter_opener                          LetterOpenerWeb::Engine
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  root 'mains#top'
  get 'mains/top'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  image      :string
#  content    :text
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validate  :image_size
  validates :content, allow_blank: true,
                      length: { maximum: 255 }
  validates :user_id, presence: true

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
    liking_users.include?(user)
  end

  private

    def image_size
      errors.add(:image, "should be less than 5MB") if image.size > 5.megabytes
    end
end

app/controllers/concerns/posts.rb
module Posts
  extend ActiveSupport::Concern

  # TODO: 'current_user.feed'が二回出てくることを回避できないか？
  def get_posts(input_words)
    if input_words
      current_user.feed.where('content LIKE ?', "%#{input_words}%")
    else
      current_user.feed
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Posts

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.new
    @posts = get_posts(params[:search]).paginate(page: params[:page])
  end

  def show
    @comment = @post.comments.build(user_id: current_user.id)
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:image, :content, :user_id)
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: 'post') do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <img id="post_image_prev" src="#" style="display:none; width:300px; height:300px; object-fit:cover;">
    <label for="post_image" class="choose_image" style="color:blue; cursor:pointer; margin:20px; padding:50px; border:dashed 2px #5b8bd0;">
      Choose an image
    </label>
    <%= form.file_field :image, id: :post_image,
                                class: 'form-control',
                                style: 'display:none;',
                                accept: 'image/jpeg,image/jpg,image/png' %>
    <span id="display_post_image"></span>
  </div>

  <div class="form-group">
    <%= form.text_area :content, id: :post_content,
                                 placeholder: "What's on your mind, #{current_user.username} ?",
                                 class: 'form-control' %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit "Upload", class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
          $('#post_image_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#post_image").change(function(){
      $('#post_image_prev').show();
      $('.choose_image').remove();
      readURL(this);
    });
  });

  $(document).ready(function(){
    $('#post_image').val("");
    $('#post_image').change(function(){
      var array = $('#post_image').val();
      var image_name = array.split("\\");
      $('#display_post_image').html(image_name[2]);
    });

    $('.post').bind('change', function(){
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
  });
</script>

app/views/posts/_post.html.erb
<div class="col-md-4">
  <!-- FIXME: 自分の投稿をいいねした場合、自分の投稿とidが重複するためmodalが動作しない -->
  <div class="card mb-4" id="post-<%= post.id %>" data-toggle="modal" data-target="#ModalCenter-<%= post.id %>">
    <%= image_tag(post.image.thumb, class: "card-img-top", alt: "#{post.user.username}\'s post") %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="ModalCenter-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="container">
          <div class="row">
            <div class="col-md-2">
              <span>
                <%= link_to user_path(post.user) do %>
                  <%= image_tag post.user.avatar.thumb, class: 'rounded-circle' %>
                <% end %>
              </span>
            </div>
            <div class="col-md-10">
              <span>
                <%= post.user.username %>
              </span>
              <i class="text-secondary ml-4">
                Posted <%= post.updated_at.strftime('%Y %-b %-d') %>
              </i>
              <p class="mt-3">
                <%= post.content %>
              </p>
              <p>
                <%= render 'likes/like_form', post: post %>
                <%= link_to post do %>
                  <i class="far fa-comment ml-2"></i>
                <% end %>
              </p>
              <% if post.user == current_user %>
                <%= link_to 'Show', post %>
                <%= link_to 'Edit', edit_post_path(post) %>
                <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= link_to post do %>
          <%= image_tag(post.image, class: "card-img-top", alt: "#{post.user.username}\'s post") %>
        <% end %>
      </div>
      <% if post.comments.any? %>
        <div class="modal-footer">
          <div class="container scroll">
            <%= render post.comments %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= provide(:title, 'Editing post') %>
<div class="container">
  <div class="row mt-4">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= provide(:title, 'Posts') %>
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <section class="user_info">
            <%= image_tag current_user.avatar, class: 'rounded-circle' %>
            <h3><%= current_user.username %></h3>
            <p><%= link_to "view profile", user_path(current_user) %></p>
            <span>Posts: <%= current_user.posts.count %></span>
          </section>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render @posts %>
  </div>
  <%= will_paginate @posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/posts/new.html.erb
<%= provide(:title, 'New Post') %>
<div class="container">
  <div class="row mt-4">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <%= render 'form', post: @post %>
          <div class="mt-4">
            <%= link_to 'Back', posts_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= provide(:title, 'Post') %>
<div class="container">
  <div class="row my-4">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <%= image_tag @post.image, class: 'card-img-top', alt: "#{@post.user.username}\s posted image" %>
        <div class="card-body">
          <p>
            <%= @post.content %>
          </p>
          <p>
            <strong>User:</strong>
            <%= @post.user.username %>
          </p>
          <p>
            <strong>Posted:</strong>
            <%= @post.updated_at.strftime('%Y %-b %-d %H:%M') %>
          </p>
          <p>
            <%= render 'likes/like_form', post: @post %>
          </p>
          <%= link_to 'Back', request.referer %>
          <%= link_to 'Edit', edit_post_path(@post) %>
          <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
      <div class="card-footer scroll">
        <div class="comment-form mb-4">
          <%= render partial: 'comments/form', locals: { comment: @comment } %>
        </div>
        <%= render @comments %>
      </div>
    </div>
  </div>
</div>