config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                             root GET      /                                       mains#top
#                        mains_top GET      /mains/top(.:format)                    mains#top
#                 new_user_session GET      /users/sign_in(.:format)                users/sessions#new
#                     user_session POST     /users/sign_in(.:format)                users/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               users/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           users/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          users/passwords#edit
#                    user_password PATCH    /users/password(.:format)               users/passwords#update
#                                  PUT      /users/password(.:format)               users/passwords#update
#                                  POST     /users/password(.:format)               users/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 users/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                users/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   users/registrations#edit
#                user_registration PATCH    /users(.:format)                        users/registrations#update
#                                  PUT      /users(.:format)                        users/registrations#update
#                                  DELETE   /users(.:format)                        users/registrations#destroy
#                                  POST     /users(.:format)                        users/registrations#create
#                  new_user_unlock GET      /users/unlock/new(.:format)             devise/unlocks#new
#                      user_unlock GET      /users/unlock(.:format)                 devise/unlocks#show
#                                  POST     /users/unlock(.:format)                 devise/unlocks#create
#                            users GET      /users(.:format)                        users#index
#                             user GET      /users/:id(.:format)                    users#show
#                letter_opener_web          /letter_opener                          LetterOpenerWeb::Engine
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

Rails.application.routes.draw do
  root 'mains#top'
  get 'mains/top'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_footer.html.erb
<footer class="py-5">
  <div class="container">
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-md-12 user-links pb-2">
          <span><%= link_to("home", posts_path) %></span>
          <span><%= link_to("new post", new_post_path) %></span>
          <span><%= link_to("explore", "#") %></span>
          <span><%= link_to("notifications", "#") %></span>
          <span><%= link_to("profile", edit_user_path(current_user)) %></span>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-12 links pb-2">
        <span><%= link_to("about us", "#") %></span>
        <span><%= link_to("support", "#") %></span>
        <span><%= link_to("press", "#") %></span>
        <span><%= link_to("api", "#") %></span>
        <span><%= link_to("jobs", "#") %></span>
        <span><%= link_to("privacy", "#") %></span>
        <span><%= link_to("terms", "#") %></span>
        <span><%= link_to("directory", "#") %></span>
        <span><%= link_to("profiles", "#") %></span>
        <span><%= link_to("hashtags", "#") %></span>
        <span><%= link_to("languages", "#") %></span>
      </div>
      <div class="col-md-12 copyright">
        <span>&copy; <%= Time.new.year %> instagram</span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light sticky-top justify-content-around" style="background-color:#fff;">
  <a class="navbar-brand" href="/posts">
    <span><i class="fab fa-instagram" style="padding-right:10px; border-right:1px solid gray"></i></span>
    <span><%= image_tag("instagram-new-logo.png", style: "height:60px;") %></span>
  </a>

  <div class="search-form text-center d-none d-sm-block">
    <%= render 'shared/posts_search' if current_page?(posts_path) %>
    <%= render 'shared/users_search' if current_page?(users_path) %>
  </div>

  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <%= link_to("#", id: "navbarDropdownMenuLink", class: "nav-link dropdown-toggle", "data-toggle": "dropdown", "data-flip": "true", "aria-haspopup": "false", "aria-expanded": "false") do %>
        <%= image_tag current_user.avatar.url, class: "rounded-circle", style: "width: 50px;" %>
      <% end %>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink" style="position: absolute;right: 0;left: auto;">
        <%= link_to "Explore", users_path, class: "dropdown-item" %>
        <!-- TODO: 通知機能実装後、通知一覧へのリンクを表示する -->
        <%#= link_to "Notifications", "#", class: "dropdown-item" %>
        <%= link_to "Your Account", user_path(current_user), class: "dropdown-item" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= favicon_link_tag('favicon.ico') %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/header' if user_signed_in? %>
    <% unless notice.blank? %>
      <p class="notice alert alert-success" role="alert" style="text-align:center; margin-bottom:-20px;"><%= notice %></p>
    <% end %>
    <% unless alert.blank? %>
      <p class="alert alert-danger" role="alert" style="text-align:center; margin-bottom:-20px;"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>